[package]
name = "git_clean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.4"
dirs = "5.0.1"
git2 = "0.17.2"
serde = "1.0.183"
serde_derive = "1.0.183"
serde_yaml = "0.9.25"
