[package]
name = "versioner_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jbg_fs = { path = "../jbg_fs" }
versioner_core = { path = "../versioner_core" }
